/**
 * Report export (Pro).
 *
 * Markdown rather than PDF: it pastes straight into Jira, Notion, GitHub and
 * email, which is where these findings actually need to land. Generating a PDF
 * would mean bundling a renderer for a worse result.
 */

function slugForFilename(url) {
  try {
    const parsed = new URL(url);
    const path = parsed.pathname.replace(/\/+$/, "").replace(/[^a-z0-9]+/gi, "-");
    return (parsed.hostname + path).replace(/^-+|-+$/g, "").slice(0, 60);
  } catch {
    return "page";
  }
}

export function buildReport(report) {
  const { summary } = report;
  const date = report.scannedAt.slice(0, 10);
  const lines = [];

  lines.push(`# Accessibility findings — ${report.title || report.url}`);
  lines.push("");
  lines.push(`- **URL:** ${report.url}`);
  lines.push(`- **Scanned:** ${report.scannedAt}`);
  lines.push(`- **Standard:** WCAG 2.2 Level AA (automated subset)`);
  lines.push(
    `- **Result:** ${summary.violations} violation(s), ` +
      `${summary.review} item(s) needing review, ` +
      `${summary.rulesPassed} of ${summary.rulesRun} checks passed`
  );
  lines.push(`- **Scope:** ${summary.elementsScanned} elements, top frame only`);
  lines.push("");
  lines.push(
    "> Automated testing detects roughly a third of accessibility barriers. " +
      "This report is evidence of the issues listed, not evidence of conformance. " +
      "Keyboard and screen reader testing by a person is still required."
  );
  lines.push("");

  const failing = report.rules.filter((rule) => rule.violations.length > 0);
  const reviewing = report.rules.filter((rule) => rule.review.length > 0);

  if (failing.length) {
    lines.push("## Violations");
    lines.push("");
    for (const rule of failing) {
      lines.push(`### ${rule.title}`);
      lines.push("");
      lines.push(
        `**WCAG ${rule.wcag.join(", ")}** · Level ${rule.level} · ` +
          `${rule.impact} impact · ${rule.violations.length} occurrence(s)`
      );
      lines.push("");
      lines.push(rule.help);
      lines.push("");
      for (const finding of rule.violations) {
        lines.push(`- ${finding.message}`);
        lines.push(`  - Selector: \`${finding.selector}\``);
        lines.push(`  - Element: \`${finding.snippet.replace(/`/g, "'")}\``);
      }
      lines.push("");
    }
  }

  if (reviewing.length) {
    lines.push("## Needs human review");
    lines.push("");
    lines.push(
      "These could not be decided automatically. Each one is a real question " +
        "that needs a person to answer — not a false alarm to dismiss."
    );
    lines.push("");
    for (const rule of reviewing) {
      lines.push(`### ${rule.title}`);
      lines.push("");
      lines.push(`**WCAG ${rule.wcag.join(", ")}** · ${rule.review.length} item(s)`);
      lines.push("");
      for (const finding of rule.review) {
        lines.push(`- ${finding.message}`);
        lines.push(`  - Selector: \`${finding.selector}\``);
      }
      lines.push("");
    }
  }

  const passed = report.rules.filter((rule) => rule.passed);
  if (passed.length) {
    lines.push("## Checks that passed");
    lines.push("");
    for (const rule of passed) {
      lines.push(`- ${rule.title} (WCAG ${rule.wcag.join(", ")})`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("Generated by A11yScope.");

  return {
    filename: `a11y-${slugForFilename(report.url)}-${date}.md`,
    mime: "text/markdown;charset=utf-8",
    content: lines.join("\n"),
  };
}
